using System.Text;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using TeamTrack.Data;
using TeamTrack.Repositories;
using TeamTrack.Services;

var builder = WebApplication.CreateBuilder(args);

// Database
builder.Services.AddDbContext<AppDbContext>(options =>
    options.UseNpgsql(builder.Configuration.GetConnectionString("DefaultConnection")));

// JWT Authentication
builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
    .AddJwtBearer(options =>
    {
        options.TokenValidationParameters = new TokenValidationParameters
        {
            ValidateIssuer = true,
            ValidateAudience = true,
            ValidateLifetime = true,
            ValidateIssuerSigningKey = true,
            ValidIssuer = builder.Configuration["Jwt:Issuer"],
            ValidAudience = builder.Configuration["Jwt:Audience"],
            IssuerSigningKey = new SymmetricSecurityKey(
                Encoding.UTF8.GetBytes(builder.Configuration["Jwt:Key"]!)),
            NameClaimType = ClaimTypes.Name,
            RoleClaimType = ClaimTypes.Role
        };
    });

builder.Services.AddAuthorization();

// CORS Setup
builder.Services.AddCors(options =>
{
    options.AddPolicy("AllowAll", policy =>
    {
        policy.AllowAnyOrigin()
              .AllowAnyMethod()
              .AllowAnyHeader();
    });
});


// Dependency Injection
builder.Services.AddMemoryCache();
builder.Services.AddTransient<IEmailService, EmailService>();
builder.Services.AddScoped(typeof(IRepository<>), typeof(Repository<>));
builder.Services.AddScoped<IAuthService, AuthService>();
builder.Services.AddScoped<IProjectService, ProjectService>();
builder.Services.AddScoped<IBugService, BugService>();
builder.Services.AddScoped<IFileService, FileService>();
builder.Services.AddScoped<IDashboardService, DashboardService>();
builder.Services.AddScoped<ICommentService, CommentService>();
builder.Services.AddScoped<IJiraImportService, JiraImportService>();
builder.Services.AddHostedService<AttachmentCleanupHostedService>();

builder.Services.AddControllers();
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen(c =>
{
    c.SwaggerDoc("v1", new() { Title = "TeamTrack", Version = "v1" });
    c.AddSecurityDefinition("Bearer", new Microsoft.OpenApi.Models.OpenApiSecurityScheme
    {
        Name = "Authorization",
        Type = Microsoft.OpenApi.Models.SecuritySchemeType.Http,
        Scheme = "Bearer",
        BearerFormat = "JWT",
        In = Microsoft.OpenApi.Models.ParameterLocation.Header,
        Description = "Token மட்டும் போடுங்க"
    });
    c.AddSecurityRequirement(new Microsoft.OpenApi.Models.OpenApiSecurityRequirement
    {
        {
            new Microsoft.OpenApi.Models.OpenApiSecurityScheme
            {
                Reference = new Microsoft.OpenApi.Models.OpenApiReference
                {
                    Type = Microsoft.OpenApi.Models.ReferenceType.SecurityScheme,
                    Id = "Bearer"
                }
            },
            Array.Empty<string>()
        }
    });
});

var app = builder.Build();

if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseMiddleware<TeamTrack.Middleware.ExceptionMiddleware>();
app.UseStaticFiles();
app.UseCors("AllowAll");

if (!app.Environment.IsDevelopment())
{
    app.UseHttpsRedirection();
}

app.UseAuthentication();
app.UseAuthorization();
app.MapControllers();

using (var scope = app.Services.CreateScope())
{
    try
    {
        var context = scope.ServiceProvider.GetRequiredService<AppDbContext>();
        var sql = @"
            CREATE TABLE IF NOT EXISTS daily_status_notes (
                id integer GENERATED BY DEFAULT AS IDENTITY,
                employee_id integer NOT NULL,
                created_by_user_id integer NOT NULL,
                note_text text NOT NULL,
                created_at timestamp with time zone NOT NULL,
                CONSTRAINT ""PK_daily_status_notes"" PRIMARY KEY (id),
                CONSTRAINT ""FK_daily_status_notes_users_employee_id"" FOREIGN KEY (employee_id) REFERENCES users (id) ON DELETE CASCADE,
                CONSTRAINT ""FK_daily_status_notes_users_created_by_user_id"" FOREIGN KEY (created_by_user_id) REFERENCES users (id) ON DELETE RESTRICT
            );
            CREATE TABLE IF NOT EXISTS personal_notes (
                id integer GENERATED BY DEFAULT AS IDENTITY,
                user_id integer NOT NULL,
                content text NOT NULL,
                created_at timestamp with time zone NOT NULL,
                note_date timestamp with time zone NOT NULL,
                priority text NOT NULL DEFAULT 'medium',
                CONSTRAINT ""PK_personal_notes"" PRIMARY KEY (id),
                CONSTRAINT ""FK_personal_notes_users_user_id"" FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
            );
            ALTER TABLE personal_notes ADD COLUMN IF NOT EXISTS priority text NOT NULL DEFAULT 'medium';
            ALTER TABLE users ADD COLUMN IF NOT EXISTS profile_picture text;
            ALTER TABLE work_items ADD COLUMN IF NOT EXISTS work_type text NOT NULL DEFAULT 'Task';
            ALTER TABLE work_items ADD COLUMN IF NOT EXISTS start_date timestamp with time zone;
            ALTER TABLE work_items ADD COLUMN IF NOT EXISTS parent_id integer;
            ALTER TABLE work_items ADD COLUMN IF NOT EXISTS labels text;
            ALTER TABLE work_items ADD COLUMN IF NOT EXISTS team text;
            ALTER TABLE work_items ADD COLUMN IF NOT EXISTS attachment_urls text;
            
            CREATE TABLE IF NOT EXISTS project_members (
                project_id integer NOT NULL,
                user_id integer NOT NULL,
                CONSTRAINT ""PK_project_members"" PRIMARY KEY (project_id, user_id),
                CONSTRAINT ""FK_project_members_projects_project_id"" FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
                CONSTRAINT ""FK_project_members_users_user_id"" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
            );

            -- Hierarchy restructuring
            CREATE TABLE IF NOT EXISTS clients (
                id integer GENERATED BY DEFAULT AS IDENTITY,
                client_number text NOT NULL,
                name text NOT NULL,
                description text,
                created_at timestamp with time zone NOT NULL,
                updated_at timestamp with time zone NOT NULL,
                CONSTRAINT ""PK_clients"" PRIMARY KEY (id)
            );
            CREATE UNIQUE INDEX IF NOT EXISTS ""IX_clients_client_number"" ON clients (client_number);

            CREATE TABLE IF NOT EXISTS products (
                id integer GENERATED BY DEFAULT AS IDENTITY,
                product_number text NOT NULL,
                name text NOT NULL,
                description text,
                project_id integer NOT NULL,
                created_at timestamp with time zone NOT NULL,
                updated_at timestamp with time zone NOT NULL,
                CONSTRAINT ""PK_products"" PRIMARY KEY (id),
                CONSTRAINT ""FK_products_projects_project_id"" FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE
            );
            CREATE UNIQUE INDEX IF NOT EXISTS ""IX_products_product_number"" ON products (product_number);

            CREATE TABLE IF NOT EXISTS modules (
                id integer GENERATED BY DEFAULT AS IDENTITY,
                module_number text NOT NULL,
                name text NOT NULL,
                description text,
                product_id integer NOT NULL,
                created_at timestamp with time zone NOT NULL,
                updated_at timestamp with time zone NOT NULL,
                CONSTRAINT ""PK_modules"" PRIMARY KEY (id),
                CONSTRAINT ""FK_modules_products_product_id"" FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE
            );
            CREATE UNIQUE INDEX IF NOT EXISTS ""IX_modules_module_number"" ON modules (module_number);

            -- Add client_id to projects
            ALTER TABLE projects ADD COLUMN IF NOT EXISTS client_id integer;
            DO $$
            BEGIN
                IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_projects_clients_client_id') THEN
                    ALTER TABLE projects ADD CONSTRAINT ""FK_projects_clients_client_id"" FOREIGN KEY (client_id) REFERENCES clients (id) ON DELETE SET NULL;
                END IF;
            END $$;

            -- Add module_id to work_items
            ALTER TABLE work_items ADD COLUMN IF NOT EXISTS module_id integer;
            DO $$
            BEGIN
                IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_work_items_modules_module_id') THEN
                    ALTER TABLE work_items ADD CONSTRAINT ""FK_work_items_modules_module_id"" FOREIGN KEY (module_id) REFERENCES modules (id) ON DELETE SET NULL;
                END IF;
            END $$;

            -- Seed default Client if not exists
            INSERT INTO clients (client_number, name, description, created_at, updated_at)
            SELECT 'CLT-001', 'Default Client', 'System generated default client', now(), now()
            WHERE NOT EXISTS (SELECT 1 FROM clients WHERE client_number = 'CLT-001');

            -- Update existing Projects that have NULL client_id to CLT-001
            UPDATE projects
            SET client_id = (SELECT id FROM clients WHERE client_number = 'CLT-001')
            WHERE client_id IS NULL;

            -- Update existing WorkItems that have NULL module_id to their project's default Module
            UPDATE work_items wi
            SET module_id = (
                SELECT m.id 
                FROM modules m
                JOIN products prd ON m.product_id = prd.id
                WHERE prd.project_id = wi.project_id
                LIMIT 1
            )
            WHERE wi.module_id IS NULL;

            -- For any WorkItem of type 'Bug' that does not have a record in the 'bugs' table, create one.
            INSERT INTO bugs (bug_number, title, description, status, work_item_id, raised_by_user_id, assigned_to_user_id, created_at, updated_at)
            SELECT 
                'BUG-' || LPAD(((SELECT COUNT(*) FROM bugs)::integer + ROW_NUMBER() OVER(ORDER BY id)::integer)::text, 3, '0'),
                title,
                description,
                CASE 
                    WHEN status = 'completed' THEN 'closed'
                    WHEN status = 'fixed' THEN 'fixed'
                    WHEN status = 'in_progress' OR status = 'waiting_customer' THEN 'in_progress'
                    ELSE 'open'
                END,
                id,
                created_by_user_id,
                assigned_to_user_id,
                created_at,
                updated_at
            FROM work_items
            WHERE work_type = 'Bug' 
              AND id NOT IN (SELECT work_item_id FROM bugs);
            ";
        context.Database.ExecuteSqlRaw(sql);

        // Dynamically resynchronize all primary key identity sequences to MAX(id) to prevent duplicate key errors
        var resetSequencesSql = @"
            DO $$
            DECLARE
                rec RECORD;
                seq_name text;
                max_id bigint;
            BEGIN
                FOR rec IN 
                    SELECT table_name 
                    FROM information_schema.tables 
                    WHERE table_schema = 'public' AND table_type = 'BASE TABLE'
                LOOP
                    BEGIN
                        seq_name := pg_get_serial_sequence(rec.table_name, 'id');
                        IF seq_name IS NULL THEN
                            IF EXISTS (SELECT 1 FROM pg_class WHERE relkind = 'S' AND relname = rec.table_name || '_id_seq') THEN
                                seq_name := rec.table_name || '_id_seq';
                            END IF;
                        END IF;

                        IF seq_name IS NOT NULL THEN
                            EXECUTE format('SELECT COALESCE(MAX(id), 0) FROM %I', rec.table_name) INTO max_id;
                            IF max_id > 0 THEN
                                EXECUTE format('SELECT setval(%L, %s, true)', seq_name, max_id);
                            ELSE
                                EXECUTE format('SELECT setval(%L, 1, false)', seq_name);
                            END IF;
                        END IF;
                    EXCEPTION WHEN OTHERS THEN
                        -- Ignore tables that lack valid id column or cause errors
                    END;
                END LOOP;

                -- Explicit sequence resets for critical work item and bug tables
                BEGIN
                    SELECT setval(pg_get_serial_sequence('bugs', 'id'), COALESCE((SELECT MAX(id) FROM bugs), 1), true);
                EXCEPTION WHEN OTHERS THEN END;
                BEGIN
                    SELECT setval(pg_get_serial_sequence('work_items', 'id'), COALESCE((SELECT MAX(id) FROM work_items), 1), true);
                EXCEPTION WHEN OTHERS THEN END;
                BEGIN
                    SELECT setval(pg_get_serial_sequence('work_item_activity_logs', 'id'), COALESCE((SELECT MAX(id) FROM work_item_activity_logs), 1), true);
                EXCEPTION WHEN OTHERS THEN END;
            END $$;
        ";
        context.Database.ExecuteSqlRaw(resetSequencesSql);
    }
    catch (Exception ex)
    {
        Console.WriteLine($"Error running DB initialization: {ex.Message}");
    }
}

app.Run();
